apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"tb-mqtt-transport","namespace":"thingsboard"},"spec":{"ports":[{"name":"mqtt","port":1883}],"selector":{"app":"tb-mqtt-transport"},"type":"ClusterIP"}}
  creationTimestamp: "2024-04-10T16:17:48Z"
  name: tb-mqtt-transport-external
  namespace: thingsboard
  resourceVersion: "77929"
  uid: 0074776e-1565-4b3f-a8fc-83629f8e85e6
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: tb-mqtt-transport
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
